language: node_js
node_js:
  - "8.0"
  - "10.0"
  - "13.0"
sudo: true
arch:
  - amd64
  - arm64
os: linux
cache:
  directories:
    - node_modules
before_script:
  - npm install
branches:
  only:
    - master
    - develop